// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelModelDownload(arg1) {
  return window['go']['main']['AIModelService']['CancelModelDownload'](arg1);
}

export function DownloadOllamaModel(arg1, arg2) {
  return window['go']['main']['AIModelService']['DownloadOllamaModel'](arg1, arg2);
}

export function DownloadVLLMModel(arg1, arg2) {
  return window['go']['main']['AIModelService']['DownloadVLLMModel'](arg1, arg2);
}

export function SetDownloadLocation(arg1) {
  return window['go']['main']['AIModelService']['SetDownloadLocation'](arg1);
}
