// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelModelDownload(arg1:string):Promise<void>;

export function DownloadOllamaModel(arg1:string,arg2:string):Promise<void>;

export function DownloadVLLMModel(arg1:string,arg2:string):Promise<void>;

export function SetDownloadLocation(arg1:string):Promise<void>;
