// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptEULAAndDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['BroadcomService']['AcceptEULAAndDownload'](arg1, arg2, arg3, arg4);
}

export function CancelDownload(arg1) {
  return window['go']['main']['BroadcomService']['CancelDownload'](arg1);
}

export function DownloadFileWithOM(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['BroadcomService']['DownloadFileWithOM'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DownloadOpsManagerWithOM(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['BroadcomService']['DownloadOpsManagerWithOM'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DownloadStemcellWithOM(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['BroadcomService']['DownloadStemcellWithOM'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetAPIToken() {
  return window['go']['main']['BroadcomService']['GetAPIToken']();
}

export function GetDownloadLocation() {
  return window['go']['main']['BroadcomService']['GetDownloadLocation']();
}

export function GetHTTPProxy() {
  return window['go']['main']['BroadcomService']['GetHTTPProxy']();
}

export function GetHTTPSProxy() {
  return window['go']['main']['BroadcomService']['GetHTTPSProxy']();
}

export function GetProductReleases(arg1) {
  return window['go']['main']['BroadcomService']['GetProductReleases'](arg1);
}

export function GetReleaseDependencies(arg1, arg2) {
  return window['go']['main']['BroadcomService']['GetReleaseDependencies'](arg1, arg2);
}

export function GetReleaseDependencySpecifiers(arg1, arg2) {
  return window['go']['main']['BroadcomService']['GetReleaseDependencySpecifiers'](arg1, arg2);
}

export function GetReleaseEULA(arg1, arg2) {
  return window['go']['main']['BroadcomService']['GetReleaseEULA'](arg1, arg2);
}

export function GetReleaseFiles(arg1, arg2) {
  return window['go']['main']['BroadcomService']['GetReleaseFiles'](arg1, arg2);
}

export function ListProducts() {
  return window['go']['main']['BroadcomService']['ListProducts']();
}

export function SetAPIToken(arg1) {
  return window['go']['main']['BroadcomService']['SetAPIToken'](arg1);
}

export function SetDownloadLocation(arg1) {
  return window['go']['main']['BroadcomService']['SetDownloadLocation'](arg1);
}

export function SetHTTPProxy(arg1) {
  return window['go']['main']['BroadcomService']['SetHTTPProxy'](arg1);
}

export function SetHTTPSProxy(arg1) {
  return window['go']['main']['BroadcomService']['SetHTTPSProxy'](arg1);
}
