// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AcceptEULAAndDownload(arg1:string,arg2:number,arg3:number,arg4:string):Promise<void>;

export function CancelDownload(arg1:number):Promise<void>;

export function DownloadFileWithOM(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<void>;

export function DownloadOpsManagerWithOM(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<void>;

export function DownloadStemcellWithOM(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<void>;

export function GetAPIToken():Promise<string>;

export function GetDownloadLocation():Promise<string>;

export function GetHTTPProxy():Promise<string>;

export function GetHTTPSProxy():Promise<string>;

export function GetProductReleases(arg1:string):Promise<Array<main.Release>>;

export function GetReleaseDependencies(arg1:string,arg2:number):Promise<Array<main.Dependency>>;

export function GetReleaseDependencySpecifiers(arg1:string,arg2:number):Promise<Array<main.DependencySpecifier>>;

export function GetReleaseEULA(arg1:string,arg2:number):Promise<main.EULA>;

export function GetReleaseFiles(arg1:string,arg2:number):Promise<Array<main.ProductFile>>;

export function ListProducts():Promise<Array<main.Product>>;

export function SetAPIToken(arg1:string):Promise<void>;

export function SetDownloadLocation(arg1:string):Promise<void>;

export function SetHTTPProxy(arg1:string):Promise<void>;

export function SetHTTPSProxy(arg1:string):Promise<void>;
